# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('father', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('Occupation', models.CharField(max_length=64)),
                ('mailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
