# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_facing'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatno', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('registered', 'Registered')], default='available', max_length=11)),
                ('Face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_posts', to='customerapp.Facing')),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_posts', to='customerapp.Blockname')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_posts', to='customerapp.Company')),
                ('floorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_posts', to='customerapp.Floors')),
                ('unitnome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_posts', to='customerapp.Unit')),
            ],
            options={
                'ordering': ('-flatno',),
            },
        ),
    ]
