# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_unitcreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitcreation',
            old_name='Face',
            new_name='face',
        ),
        migrations.RenameField(
            model_name='unitcreation',
            old_name='unitnome',
            new_name='unitno',
        ),
    ]
