# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0010_auto_20200219_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitcreation',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerapp_unitcreations', to='customerapp.Company'),
        ),
    ]
