# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_auto_20200219_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatnumber', models.CharField(max_length=10)),
                ('sft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerapp_flatcreations', to='customerapp.Unit')),
            ],
            options={
                'ordering': ('-flatnumber',),
            },
        ),
    ]
