# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0012_flatcreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatcreation',
            name='sft',
        ),
        migrations.AlterModelOptions(
            name='unitcreation',
            options={},
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='bname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Blockname'),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Company'),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Facing'),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='floorno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Floors'),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='unitno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Unit'),
        ),
        migrations.DeleteModel(
            name='FlatCreation',
        ),
    ]
