# Generated by Django 3.0.3 on 2020-03-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0017_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('price', models.FloatField()),
                ('pcharge', models.FloatField()),
                ('grossprice', models.FloatField()),
                ('discount', models.FloatField()),
                ('netprice', models.FloatField()),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Amenities')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Company')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Facing')),
                ('flatno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.UnitCreation')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Scheme')),
                ('sft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Unit')),
                ('unittype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.UnitType')),
            ],
        ),
    ]
