# Generated by Django 3.0.3 on 2020-03-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0018_unitcosting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitcosting',
            old_name='scheme',
            new_name='schemetype',
        ),
        migrations.AlterField(
            model_name='unitcosting',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.Customer'),
        ),
    ]
